ERROR:root:Nieznany wyjątek
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 7, in load_player_data
    with open(filepath, newline='', encoding='utf-8') as csvfile:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Data/players.csv'
ERROR:root:Błąd domenowy
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 11, in load_player_data
    row['goals'] = int(row['goals'])
                   ~~~^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'twenty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 16, in load_player_data
    raise InvalidStatFormatError(
        f"Błąd danych zawodnika {row.get('name')}: {e}"
    ) from e
exceptions.InvalidStatFormatError: Błąd danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
ERROR:root:Błąd domenowy
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 18, in load_player_data
    row['goals'] = int(row['goals'])
                   ~~~^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'twenty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 23, in load_player_data
    raise InvalidStatFormatError(
        f"Błąd danych zawodnika {row.get('name')}: {e}"
    ) from e
exceptions.InvalidStatFormatError: Błąd danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
ERROR:root:Błąd domenowy
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 18, in load_player_data
    row['goals'] = int(row['goals'])
                   ~~~^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'twenty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 23, in load_player_data
    raise InvalidStatFormatError(
        f"Błąd danych zawodnika {row.get('name')}: {e}"
    ) from e
exceptions.InvalidStatFormatError: Błąd danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
ERROR:root:Błąd domenowy
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 18, in load_player_data
    row['goals'] = int(row['goals'])
                   ~~~^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'twenty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 23, in load_player_data
    raise InvalidStatFormatError(
        f"Błąd danych zawodnika {row.get('name')}: {e}"
    ) from e
exceptions.InvalidStatFormatError: Błąd danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
ERROR:root:Nieznany wyjątek
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 22, in load_player_data
    row['matches_played'] = int(row['matches_played'])
                            ~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:root:Nieznany wyjątek
Traceback (most recent call last):
  File "/Users/wiktorbanek/Football Stats Analyzer/main.py", line 9, in main
    players = load_player_data("Data/players.csv")
  File "/Users/wiktorbanek/Football Stats Analyzer/analyzer.py", line 22, in load_player_data
    row['matches_played'] = int(row['matches_played'])
                            ~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
WARNING:root:Błąd w danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
WARNING:root:Błąd w danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
WARNING:root:Błąd w danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
WARNING:root:Błąd w danych zawodnika Cristiano Ronaldo: invalid literal for int() with base 10: 'twenty'
